version: '3.8'

services:
  pirateflix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pirateflix
    ports:
      - "8080:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    restart: unless-stopped

